spring.application.name=spring
server.port=${PORT:5005}
spring.profiles.active=${SPRING_PROFILE:local} 

# Database - Connexion Railway
spring.datasource.url=jdbc:postgresql://shinkansen.proxy.rlwy.net:45683/railway
spring.datasource.username=postgres
spring.datasource.password=nIsLjyxEsePoGqUUJHjMQhgMIvHmyIVr
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-init-sql=SELECT 1
spring.datasource.hikari.maximum-pool-size=2

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SSL Configuration
spring.datasource.hikari.data-source-properties.sslmode=require
spring.datasource.hikari.data-source-properties.ssl=true

# File upload
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Configuration Brevo pour l'API HTTP
brevo.api.key=${BREVO_API_KEY} 
brevo.api.url=https://api.brevo.com/v3

# ==============================================
# APPLICATION EMAIL SETTINGS
# ==============================================
# L'email qui apparaîtra comme expéditeur (doit être vérifié dans Brevo)
app.email.from=ajrberuf@gmail.com
# Où envoyer les notifications (peut être le même ou différent)
app.email.team=ajrberuf@gmail.com
app.name=VINA Association

# Configuration de la session
server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.max-age=1800
server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.cookie.path=/

# Cloudinary Configuration (avec variables d'environnement)
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
